name = "html-heaven"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

routes = [
  { pattern = "htmlheaven.com", custom_domain = true },
  { pattern = "www.htmlheaven.com", custom_domain = true },
]

[[d1_databases]]
binding = "DB"
database_name = "html-heaven-db"
database_id = "57fe5a07-6369-4be0-a2eb-253cc2614231"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
