import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { SessionProvider } from "@/components/SessionProvider";
import { OwnershipProvider } from "@/components/OwnershipProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const SITE_URL = "https://htmlheaven.com";
const SITE_TITLE = "HTML Heaven — open-source home for HTML5 apps";
const SITE_DESC =
  "The open-source hub for self-contained HTML5 apps. Tower defense, flashcards, timers, game counters, AI skills — all running right in your browser. Built by the community.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: SITE_TITLE,
    template: "%s — HTML Heaven",
  },
  description: SITE_DESC,
  applicationName: "HTML Heaven",
  keywords: [
    "HTML5 apps",
    "open source",
    "web games",
    "single-file HTML",
    "vibe coding",
    "browser apps",
    "AI skills",
  ],
  authors: [{ name: "HTML Heaven", url: SITE_URL }],
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: "HTML Heaven",
    title: SITE_TITLE,
    description: SITE_DESC,
    // Falls back to /opengraph-image generated by src/app/opengraph-image.tsx
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_TITLE,
    description: SITE_DESC,
    // Falls back to /twitter-image generated by src/app/twitter-image.tsx
  },
  robots: {
    index: true,
    follow: true,
  },
};

export const viewport: Viewport = {
  themeColor: "#0f0f14",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <SessionProvider>
          <OwnershipProvider>
            <Suspense fallback={<div className="h-14 border-b border-border/50" />}>
              <Navbar />
            </Suspense>
            <main className="flex-1">{children}</main>
            <Footer />
          </OwnershipProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
